import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class JokesService {

    private jokes = [
        "Why did the scarecrow get promoted? He was outstanding in his field!",
        "Why don’t scientists trust atoms? Because they make up everything!",
        "Why did the bicycle fall over? It was two-tired!",
        "Why did the mushroom go to the party alone? Because he's a fungi!",
        "Why don’t skeletons fight each other? They don’t have the guts!",
        "Why did the math book look sad? It had too many problems!",
        "What’s orange and sounds like a parrot? A carrot!",
        "How does a penguin build its house? Igloos it together!",
        "Why do cows wear bells? Because their horns don’t work!",
        "What did one wall say to the other? I'll meet you at the corner!",
        "Why can’t you give Elsa a balloon? She'll let it go!",
        "How do you organize a space party? You planet!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "Why are elevator jokes so good? They work on many levels!",
        "What did the big flower say to the little flower? 'Hey, bud!'",
        "Why can’t you hear a pterodactyl in the bathroom? Because the P is silent!",
        "How does the ocean say hello? It waves!",
        "Why do fish live in saltwater? Because pepper makes them sneeze!",
        "Why are ghosts so bad at lying? Because you can see right through them!",
        "Why did the coffee file a police report? It got mugged!",
        "What’s brown and sticky? A stick!",
        "Why are frogs so happy? They eat whatever bugs them!",
        "How do you catch a squirrel? Climb a tree and act like a nut!",
        "What did the digital clock say to its mother? 'Look, Ma! No hands!'",
        "Why don’t some couples go to the gym? Because some relationships don’t work out!",
        "What did one hat say to the other? 'Stay here, I’m going on ahead!'",
        "Why did the cookie go to the hospital? Because it felt crumby!",
        "What does a nosy pepper do? Gets jalapeño business!",
        "Why are teddy bears never hungry? Because they’re always stuffed!",
        "What did the buffalo say to his son when he left? Bison!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What do you call fake spaghetti? An impasta!",
        "How do you make a tissue dance? Put a little boogie in it!",
        "Why couldn’t the leopard play hide and seek? Because he was always spotted!",
        "Why did the skeleton go to the party alone? He had no body to go with!",
        "Why are spiders great web designers? Because they know their net-working!",
        "Why don’t eggs tell jokes? Because they might crack up!",
        "What did the fish say when it hit the wall? Dam!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "Why did the bicycle stand by itself? Because it was two-tired!",
        "What does a cloud wear under his raincoat? Thunderwear!",
        "Why did the duck get a job? He was quacking up!",
        "What did the blanket say to the bed? 'Don’t worry, I’ve got you covered!'",
        "Why did the farmer win an award? He was outstanding in his field!",
        "Why did the grape stop in the middle of the road? Because it ran out of juice!",
        "Why don’t we see giraffes in school? They always stick their necks out!",
        "What’s a tree’s favorite drink? Root beer!",
        "Why don’t scientists trust atoms? They make up everything!",
        "Why did the banana go to the doctor? It wasn’t peeling well!",
        "Why was the math book sad? It had too many problems!",
        "How does a dog stop a video? By hitting the ‘paws’ button!",
        "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus!",
        "How do you talk to giants? Use big words!",
        "Why did the computer go to the doctor? Because it had a virus!",
        "Why was the stadium so cool? It was filled with fans!",
        "What did the tree say to spring? 'What a re-leaf!'",
        "How do celebrities stay cool? They have many fans!",
        "What did the bee say to the flower? 'Hey, bud!'",
        "Why did the belt get arrested? It was holding up pants!",
        "Why are frogs so happy? Because they eat whatever bugs them!",
        "What did the coffee say to the sugar? 'You make life sweet!'",
        "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears!",
        "What did one snowman say to the other? 'Do you smell carrots?'",
        "How do you throw a space party? You planet!",
        "Why did the golfer bring an extra pair of pants? In case he got a hole in one!",
        "How does the ocean say hi? It waves!",
        "Why did the scarecrow get an award? He was outstanding in his field!",
        "What did the blanket say to the bed? 'I’ve got you covered!'",
        "Why was the broom late? It swept in!",
        "What do you call cheese that isn't yours? Nacho cheese!",
        "Why did the orange stop? It ran out of juice!",
        "Why did the dog sit in the shade? It didn’t want to be a hot dog!",
        "Why are calendars so popular? They have lots of dates!",
        "Why don’t some fish play piano? They can’t tune-a fish!",
        "What does a snowman do in summer? Chill!",
        "What do you call a pig that does karate? A pork chop!",
        "What do you call a bear with no teeth? A gummy bear!",
        "What did one plate say to the other? 'Lunch is on me!'",
        "Why did the banana go to the doctor? It wasn’t peeling well!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the boy bring a ladder to school? He wanted to go to high school!",
        "How do you make a tissue dance? Put a little boogie in it!",
        "What do you call an alligator in a vest? An investigator!",
        "Why did the cookie go to the doctor? It felt crumby!",
        "Why did the man put his money in the blender? He wanted to make some dough!",
        "Why are fish bad at basketball? They don’t want to get caught!",
        "What did one wall say to the other? 'I’ll meet you at the corner!'",
        "Why did the tree go to therapy? It had too many branches of issues!",
        "What did the grape do when it got stepped on? It let out a little wine!",
        "Why did the stadium get so hot? All the fans left!",
        "What do you call a bear stuck in the rain? A drizzly bear!",
        "Why are ghosts bad liars? Because they’re transparent!",
        "Why did the skeleton stay calm? Nothing got under its skin!",
        "What did the clock do when it was hungry? It went back four seconds!",
        "Why don’t scientists trust atoms? They make up everything!",
        "How do you catch a squirrel? Climb a tree and act like a nut!",
        "What did one eye say to the other? 'Between us, something smells!'",
        "Why did the football team go to the bank? To get their quarterback!",
        "Why did the bank teller cross the road? To check on the balance!",
        "What did the baby corn say to the mama corn? 'Where’s popcorn?'",
        "How do you make a tissue dance? Put a little boogie in it!",
        "Why did the scarecrow get promoted? He was outstanding in his field!",
        "How does a snowman get around? By riding an “icicle”!"    
    ]

    constructor() { }

    getJoke(): string {
        return this.jokes[Math.floor(Math.random() * this.jokes.length)];
    }
}